#!/bin/bash
#16
#1000000000000000101000000000000011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000101000000000000011000000000000000000000000000000000000000000
s=$(head -2 ~/.prog/bin/cgol2 | tail -1 )
s=${s:1:100}
t=$(head -3 ~/.prog/bin/cgol2 | tail -1 )
t="0"${t:1:10000000000}
l=$((s*s))
s1=$((s+1))
itera=-1
while test $# -gt 0; do
           case "$1" in
                -a)
                    shift
                    a=$1
                    shift
                    ;;
                -n)
                    shift
                    n=$1
                    shift
                    ;;
                -s)
                    shift
                    s=$1
                    shift
                    ;;
                -f)
                    shift
                    file=$1
                    shift
                    ;;
                -h)
                    shift
                    echo discription && exit
                    shift
                    ;;
                *)
                   echo "$1 is not a recognized flag!"
                   return 1;
                   ;;
          esac
done
if [ "$file" != "" ]
then
s=0
until [ "$s" == "$count" ]
do
count=$((count+1))
line=$(head -$count $file | tail -1 )
tmp=$(echo $line | wc -c)
s=$((tmp-1))
t="$t$line"
done
fi
until [ "$done" == "1" ]
do
itera=$((itera+1))
#
clear
#
b=0
h=1
until [ "$count" == "$s" ]
do
count=$((count+1))
#
temp=${t:$h:$s}
subcount=0
out=""
until [ "$subcount" == "$s1" ]
do
out=$out" "${temp:$subcount:1}
subcount=$((subcount+1))
done
#
echo $out
h=$((h+s))
done
echo "" #&& sleep 1s
echo "Iteration: $itera"
until [ "$f" == "$l" ]
do
f=$((f+1))
f1=$((f+1))
f2=$((f1-s))
f3=$((f2-1))
f4=$((f3-1))
f5=$((f-1))
f8=$((f1+s))
f7=$((f8-1))
f6=$((f7-1))
[ "${f2:0:1}" == "-" ] && f2=$((f2+l))
[ "${f3:0:1}" == "-" ] && f3=$((f3+l))
[ "${f4:0:1}" == "-" ] && f4=$((f4+l))
[ "${f5:0:1}" == "-" ] && f5=$((f5+l))
#subtract all by "l" and see whether negative or pos
t6=$((f6-l)) && [ "${t6:0:1}" == "-" ] || f6=$t6
t7=$((f7-l)) && [ "${t7:0:1}" == "-" ] || f7=$t7
t8=$((f8-l)) && [ "${t8:0:1}" == "-" ] || f8=$t8

ft=$((${t:$f1:1}+${t:$f2:1}+${t:$f3:1}+${t:$f4:1}+${t:$f6:1}+${t:$f7:1}+${t:$f8:1}+${t:$f5:1}))
[ "${t:$f:1}" == "0" ] && [ "$ft" == "0" ] && b=$b"0"
[ "${t:$f:1}" == "0" ] && [ "$ft" == "1" ] && b=$b"0"
[ "${t:$f:1}" == "0" ] && [ "$ft" == "2" ] && b=$b"0"
[ "${t:$f:1}" == "0" ] && [ "$ft" == "3" ] && b=$b"1"
[ "${t:$f:1}" == "0" ] && [ "$ft" == "4" ] && b=$b"0"
[ "${t:$f:1}" == "0" ] && [ "$ft" == "5" ] && b=$b"0"
[ "${t:$f:1}" == "0" ] && [ "$ft" == "6" ] && b=$b"0"
[ "${t:$f:1}" == "0" ] && [ "$ft" == "7" ] && b=$b"0"
[ "${t:$f:1}" == "0" ] && [ "$ft" == "8" ] && b=$b"0"

[ "${t:$f:1}" == "1" ] && [ "$ft" == "0" ] && b=$b"0"
[ "${t:$f:1}" == "1" ] && [ "$ft" == "1" ] && b=$b"0"
[ "${t:$f:1}" == "1" ] && [ "$ft" == "2" ] && b=$b"1"
[ "${t:$f:1}" == "1" ] && [ "$ft" == "3" ] && b=$b"1"
[ "${t:$f:1}" == "1" ] && [ "$ft" == "4" ] && b=$b"0"
[ "${t:$f:1}" == "1" ] && [ "$ft" == "5" ] && b=$b"0"
[ "${t:$f:1}" == "1" ] && [ "$ft" == "6" ] && b=$b"0"
[ "${t:$f:1}" == "1" ] && [ "$ft" == "7" ] && b=$b"0"
[ "${t:$f:1}" == "1" ] && [ "$ft" == "8" ] && b=$b"0"
done
[ "$t" == "$b" ] && done=1
t=$b
count=0
f=0
done

